### ISSUE TITLE
How to dynamically set baseURL

### ISSUE THREAD

**Issue by marceloavf** [christianmalek/vuex-rest-api#40]
Some of my clients will receive some notifications from their servers, so I need to dynamically set the `baseURL` for each one of them, the only way I find it right now is passing them in the `localStorage` and consuming that before config are set.

Is there another way to dynamically change the baseURL?

Thanks!

**Comment by christianmalek** [comment]
Changing the pathes after the creation of the store isn't possible because the pathes are only accessible via the closure `completePathFn` function.

**Comment by christianmalek** [comment]
@marceloavf I edited my answer.

**Comment by marceloavf** [comment]
Great idea!
How can I create another instance of Vapi inside mounted/created Vue hook?

**Comment by christianmalek** [comment]
I just revisited my code and saw that it doesn't work at the moment. I'm sorry. :/

I'll test it soon and let you know.

**Comment by marceloavf** [comment]
No problem @christianmalek, thanks for the help and information.
I will try to figure out another way, just for now.

**Comment by christianmalek** [comment]
@marceloavf Sorry for the late answer. I forgot this issue...

I just revisited the source code and come to the conclusion that I won't change it. I *could* make the baseURL accessible and create a public method in the store so that you can change the baseURLs of the resources before you create the store. But this will make the code dirty and hacky and that's not what I want.

Maybe someone else has a better idea. But for now I can't help you further. :(

**Comment by marceloavf** [comment]
No problem @christianmalek, don't worry, I already found a way to change it by using `localStorage`.

Since I use `electron with vue`, there is no secure problem, thank you for your answer!
