### ISSUE TITLE
Callback when rest call completes

### ISSUE THREAD

**Issue by liftyourgame** [christianmalek/vuex-rest-api#91]
How would you specify a callback so you can have code execute once the REST call completes?

**Comment by christianmalek** [comment]
Hello @liftyourgame,

You can do it with async-await (or promises) outside of the initialization of the store. This is useful if you have to handle every call individually.
```js
async foo() {
  try {
    await this.someAction();
    // success
  } catch (error) {
    // error
  }
}
```

Otherwise you can use [onSuccess](https://christianmalek.github.io/vuex-rest-api/api.html#onsuccess) and [onError](https://christianmalek.github.io/vuex-rest-api/api.html#onerror).

**Comment by christianmalek** [comment]
I'll close this due to inactivity. Feel free to open a new issue.
